import colors from "./utils/Colors";

export const darkTheme = {
  prevNextButtons: {
    bg: colors.gray["900"],
    arrow: colors.gray["500"],
    hoverBg: colors.gray["800"],
    prevText: colors.suvaGray,
    title: colors.gray["300"],
  },
  brands: {
    ...colors.brands,
  },
  auth: {
    bg: colors.black.appBlack,
    header: {
      bg: colors.gray["900"],
      text: colors.gray["400"],
    },
    home: {
      bg: colors.black.appBlack,
      box1: {
        heading: colors.gray["300"],
        defiProject: colors.green["400"],
        subHeading: colors.gray["600"],
      },
      box2: {
        bg: colors.darkGrayishBlue,
        heading: colors.white,
        link: colors.gray["500"],
        linkBorder: colors.gray["77"],
        cardBg: colors.gray["800"],
        image: colors.gray["300"],
        cardHead: colors.gray["200"],
        cardSubHead: colors.gray["500"],
        divider: colors.veryLightGray,
      },
      box3: {
        bg: colors.black.appBlack,
        head: colors.gray["300"],
        subHead: colors.gray["500"],
        points: colors.gray["500"],
        iconBg: colors.green["900"],
        buttonBg: colors.gray["900"],
        buttonText: colors.gray["400"],
      },
      box4: {
        bg: colors.black.appBlack,
        heading: colors.gray["200"],
        card1: colors.papayaWhip,
        card2: colors.harmonies,
        card3: colors.hawkiesBlue,
        title: colors.gray["900"],
        description: colors.gray["500"],
      },
      box5: {
        bg: colors.black.appBlack,
        heading: colors.gray["300"],
        cardBg: colors.gray["900"],
        name: colors.gray["300"],
        company: colors.gray["500"],
        feedback: colors.gray["300"],
      },
      footer: {
        bg: colors.gray["900"],
        text: colors.white,
      },
    },
    setup: {
      border: colors.gray["700"],
      bg: colors.gray["900"],
      heading: colors.gray["300"],
      text: colors.gray["300"],
      avatarBorder: colors.avatarBorder,
      icon: colors.gray["500"],
    },
    reset: {
      border: colors.pattensBlue,
      bg: colors.white,
    },
    signin: {
      arrowIcon: colors.gray["500"],
      privacyPolicy: colors.mediumStateBlue,
      discordText: colors.white,
      discordBorder: colors.avatarBorder,
      discordButton: colors.mediumStateBlue,
      slackText: colors.white,
      slackButton: colors.brands.slack,
      slackBorder: colors.avatarBorder,
      divider: colors.veryLightGray,
      iconsBg: colors.gray["800"],
      twitter: colors.buttonBlue,
      mail: colors.gray["500"],
      emailBorder: colors.gray["700"],
      emailText: colors.gray["300"],
      forgotMessage: colors.gray["500"],
      otp: colors.vividBlue,
      otpMessage: colors.gray["500"],
      bg: colors.gray["900"],
      border: colors.gray["700"],
      progressBar: colors.blue["500"],
    },
    onboarding: {
      bg: colors.gray["900"],
    },
  },
  createStudioLoader: {
    bg: colors.gray["900"],
  },
  discordIntegration: {
    description: colors.gray["500"],
    createCardBorder: colors.green["500"],
  },
  border: {
    ultraSubtle: colors.gray["400"],
  },
  notionImport: {
    checkIcon: colors.green["500"],
    heading: colors.gray["300"],
    failedMsg: colors.red["300"],
    uploadBoxBg: colors.green["800"],
    uploadDisabled: colors.gray["900"],
    infoIcon: colors.gray["500"],
    importText: colors.gray["500"],
    border: colors.gray["700"],
    importTypeHover: colors.gray["900"],
  },
  postInFeed: {
    cardBg: colors.gray["900"],
    textLight: colors.gray["500"],
    text: colors.gray["300"],
    textSelect: colors.vividBlue,
    textBlack: colors.gray["300"],
    border: colors.gray["700"],
    labelBg: colors.gray["900"],
    commentsBg: colors.gray["800"],
    selCommentBg: colors.gray["700"],
    likeOverlayBg: colors.blackPearl,
  },
  notifications: {
    bg: colors.gray[900],
    spinner: colors.green["500"],
    inboxIcon: colors.blue["600"],
    emptyHeading: colors.gray["200"],
    emptyMessage: colors.gray["300"],
    endBorder: colors.gray["700"],
    filters: {
      border: colors.gray["800"],
      selected: {
        text: colors.green["200"],
        bg: colors.green["900"],
      },
      unSelected: {
        text: colors.gray["400"],
        bg: colors.gray["800"],
      },
    },
    messages: {
      hoverBg: colors.gray["800"],
      imageBorder: colors.gray["700"],
      imageText: colors.gray["300"],
      message: colors.gray["300"],
      repliesText: colors.gray["500"],
      time: colors.gray["500"],
    },
    primaryButton: {
      color: colors.white,
      border: colors.avatarBorder,
    },
    tabNav: {
      bg: colors.gray["800"],
      selected: {
        bg: colors.gray["900"],
        text: colors.white,
      },
      unSelected: {
        text: colors.gray["500"],
      },
    },
    users: {
      black: colors.white,
      selectedBorder: colors.blue["500"],
      border: colors.gray["700"],
      counterBg: colors.green["600"],
      counter: colors.white,
    },
    settings: {
      box1: {
        bg: colors.gray["900"],
        border: colors.gray["700"],
        heading: colors.gray["500"],
        text: colors.gray["300"],
        xIcon: colors.gray["100"],
      },
      box2: {
        platform: colors.gray["300"],
        border: colors.gray["700"],
      },
    },
  },
  bipMarks: {
    border: colors.gray["700"],
    scrollBg: colors.gray["800"],
    icon: colors.blue["600"],
    endMessage: colors.gray["300"],
    bipMessage: colors.gray["400"],
    trashIcon: colors.gray["700"],
  },
  contributorsList: {
    stack: {
      bg: colors.gray["600"],
    },
    list: {
      text: colors.gray["500"],
      cardHoverBg: colors.gray["900"],
      name: colors.gray["200"],
    },
  },
  canvasItem: {
    text: colors.gray["600"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    nodeName: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  fakeSelection: {
    text: colors.white,
    bg: colors.selectBlue,
  },
  languageItem: {
    text: colors.gray["600"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    nodeName: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  brachItem: {
    text: colors.gray["500"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  collectionItem: {
    item: colors.gray["600"],
    itemHoverBg: colors.gray["800"],
    nodeName: colors.gray["500"],
    hoverBg: colors.white07,
    selectedNodeName: colors.gray["300"],
  },
  toolbar: {
    bg: colors.gray["800"],
    activeIcon: colors.blue["500"],
    normalIcon: colors.gray["300"],
  },
  blockWrapper: {
    border: colors.black.appBlack,
    hoverBg: colors.gray["900"],
    username: colors.gray["200"],
    time: colors.gray["500"],
    icon: colors.gray["600"],
    highlight: colors.gray["800"],
  },
  table: {
    border: colors.blue["300"],
  },
  callout: {
    info: colors.gray["900"],
    tip: colors.blue["800"],
    success: colors.green["1000"],
    alert: colors.yellow["1000"],
    danger: colors.red["1000"],
    hintText: colors.gray["500"],
  },
  image: {
    caption: colors.gray["600"],
  },
  drawio: {
    hintText: colors.gray["700"],
    emptyHintText: colors.gray["400"],
    imageBg: colors.white,
  },
  headings: {
    text: colors.gray["200"],
  },
  chip: {
    bg: colors.gray["700"],
    icon: colors.gray["500"],
  },
  toast: {
    success: colors.green["800"],
    error: colors.red["800"],
    warning: colors.yellow["800"],
    info: colors.blue["700"],
    text: colors.gray["300"],
    closeIcon: colors.gray["500"],
    bg: colors.gray["900"],
    icon: colors.white,
  },
  verticalDivider: {
    border: colors.gray["600"],
  },
  imageWithName: {
    color: colors.gray["300"],
    border: colors.gray["300"],
  },
  element: {
    bg: colors.yellow["900"],
  },
  checklistBlock: {
    text: colors.gray["300"],
  },
  orderedListBlock: {
    text: colors.gray["300"],
  },
  unOrderedListBlock: {
    text: colors.gray["300"],
  },
  attachmentBlock: {
    bg: colors.gray["800"],
    acceptBg: colors.green["800"],
    rejectBg: colors.red["800"],
    selectedBorder: colors.blue["300"],
    border: colors.gray["300"],
  },
  codeBlock: {
    text: colors.gray["83"],
    bg: colors.lightHexaChromeBlack,
    hintText: colors.gray["500"],
  },
  quoteBlock: {
    text: colors.gray["300"],
    borderColor: colors.gray["600"],
  },
  inlineCode: {
    text: colors.gray["200"],
  },
  defaultBlock: {
    text: colors.gray["300"],
  },
  subTextBlock: {
    text: colors.gray["500"],
  },
  dividerBlock: {
    default: colors.gray["500"],
    selected: colors.gray["900"],
  },
  excalidraw: {
    hintText: colors.gray["300"],
  },
  imageBlock: {
    bg: colors.gray["800"],
    acceptBg: colors.green["800"],
    rejectBg: colors.red["800"],
    selectedBorder: colors.blue["300"],
    border: colors.gray["300"],
    resize: colors.black["0"],
    resizeBg: colors.white,
  },
  TOCBlock: {
    bg: colors.gray["800"],
    textColor: colors.gray["300"],
  },
  canvasHeaderActions: {
    buttonGroups: {
      border: colors.white,
    },
    cancel: colors.red["400"],
    lightText: colors.gray["500"],
    overlayBg: colors.gray["900"],
    inputBorder: colors.gray["700"],
    message: colors.gray["300"],
  },
  canvasUserPermissions: {
    bg: colors.gray["900"],
    avatarText: colors.gray["300"],
    anchorBg: colors.gray["800"],
  },
  layout: {
    sidebar: {
      bg: colors.gray["900"],
      text: colors.gray["300"],
    },
    user: {
      text: colors.white,
      bg: colors.white05,
      hoverBg: colors.white01,
      notificationCountBg: colors.green["600"],
    },
    bg: colors.black.appBlack,
  },
  studioLayout: {
    bg: colors.black.appBlack,
    white: colors.black.appBlack,
    headerBg: colors.gray["900"],
  },
  previewEditor: {
    bg: colors.black.appBlack,
    headerBg: colors.gray["900"],
    headerBorder: colors.gray["700"],
    canvasTitle: colors.gray["200"],
  },
  layoutFAB: {
    bg: colors.gray["800"],
    color: colors.gray["400"],
  },
  reelCard: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    avatarBorder: colors.gray["300"],
    followButton: colors.gray["500"],
    text: {
      username: colors.gray["300"],
      studioname: colors.gray["300"],
      grayLight: colors.gray["500"],
      time: colors.gray["300"],
      reelMessage: colors.gray["300"],
      repliesText: colors.gray["500"],
      hintText: colors.gray["300"],
    },
    editor: {
      bg: colors.gray["900"],
      border: colors.gray["700"],
      text: colors.gray["300"],
      button: {
        text: colors.gray["500"],
        hoverBg: colors.gray["10"],
        hoverText: colors.gray["700"],
      },
      link: {
        hoverBorder: colors.gray["700"],
        text: colors.gray["300"],
        hoverText: colors.gray["600"],
      },
    },
    comment: {
      bg: colors.gray["800"],
      text: colors.gray["300"],
      time: colors.gray["300"],
      downIcon: colors.gray["300"],
      repliesText: colors.gray["500"],
    },
  },
  about: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    avatarBorder: colors.gray["300"],
    editButtonHoverBg: colors.gray["800"],
    tokenBorder: colors.gray["500"],
    text: {
      avatarText: colors.gray["300"],
      displayName: colors.gray["300"],
      handle: colors.gray["500"],
      description: colors.gray["300"],
      joinButton: colors.green["500"],
      joinedButton: colors.gray["500"],
      token: colors.gray["500"],
      editIconColor: colors.gray["600"],
      calendarIcon: colors.gray["600"],
      date: colors.gray["600"],
      twitterIcon: colors.gray["600"],
      globeIcon: colors.gray["600"],
      linkColor: colors.blue["400"],
      linkHoverColor: colors.blue["300"],
      location: colors.gray["600"],
      followCount: colors.gray["600"],
      pencilIcon: colors.gray["600"],
    },
  },
  newRightRail: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
  },
  profile: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    avatarBorder: colors.gray["300"],
    studioBorder: colors.gray["700"],
    editButtonHoverBg: colors.gray["800"],
    text: {
      username: colors.gray["300"],
      handle: colors.gray["500"],
      bio: colors.gray["300"],
      followButton: colors.green["500"],
      followingButton: colors.gray["500"],
      calendarIcon: colors.gray["600"],
      date: colors.gray["600"],
      twitterIcon: colors.gray["600"],
      globeIcon: colors.gray["600"],
      linkColor: colors.blue["400"],
      linkHoverColor: colors.blue["300"],
      location: colors.gray["600"],
      followCount: colors.gray["600"],
      pencilIcon: colors.gray["600"],
    },
  },
  studioCard: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    text: {
      displayname: colors.gray["300"],
      handle: colors.gray["500"],
      joinButton: colors.gray["500"],
      joinedButton: colors.gray["500"],
      description: colors.gray["300"],
      members: colors.gray["400"],
    },
  },
  userCard: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    text: {
      username: colors.gray["300"],
      handle: colors.gray["500"],
      followButton: colors.gray["500"],
      followingButton: colors.gray["500"],
      followers: colors.gray["400"],
    },
  },
  addComment: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    cancel: colors.gray["500"],
    postBg: colors.green["500"],
    postBorder: colors.green["500"],
    postText: colors.white,
    errorColor: colors.pinkRed,
  },
  addReel: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    heading: colors.gray["300"],
    closeIcon: colors.gray["200"],
    hintText: colors.gray["200"],
  },
  thread: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    menuBg: colors.gray["900"],
    highlightedTextBorder: colors.orange["600"],
    text: {
      highlightedText: colors.gray["500"],
      date: colors.gray["500"],
      message: colors.gray["300"],
      username: colors.gray["300"],
      repliesText: colors.gray["300"],
      resolve: colors.gray["500"],
    },
  },
  reel: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    comment: {
      bg: colors.gray["800"],
      text: colors.gray["300"],
      time: colors.gray["300"],
      downIcon: colors.gray["300"],
      repliesText: colors.gray["500"],
      highlightTextBorder: colors.yellow["400"],
      highlightText: colors.gray["500"],
      message: colors.gray["300"],
    },
  },
  canvasHeader: {
    bg: colors.gray["900"],
  },
  canvasTitle: {
    title: colors.gray["300"],
    border: colors.gray["700"],
    hintMessage: colors.gray["400"],
    loginMessage: colors.gray["400"],
    loginButton: colors.green["400"],
  },
  rightRailContainer: {
    bg: colors.gray["900"],
  },
  canvasTimeline: {
    itemBg: colors.gray["500"],
    commit: {
      hoverBg: colors.gray["800"],
      date: colors.gray["500"],
      message: colors.gray["300"],
    },
  },
  mentionsInput: {
    users: {
      bg: colors.gray["900"],
      selectedBg: colors.gray["800"],
    },
    mentionedText: colors.green["500"],
  },
  blockReactions: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
  },
  toc: {
    bg: colors.gray["900"],
    text: colors.gray["300"],
    activeText: colors.gray["500"],
    border: colors.gray["700"],
  },
  rightRailPermissions: {
    lightText: colors.gray["500"],
    darkText: colors.gray["300"],
    veryDarkText: colors.gray["0"],
    copyLink: colors.blue["500"],
    inviteUsers: colors.blue["500"],
  },
  canvasPublicAccessOverlay: {
    bg: colors.gray["900"],
    item: colors.green["600"],
    text: colors.gray["400"],
    apply: colors.green["500"],
    cancel: colors.gray["500"],
  },
  collectionPublicAccessOverlay: {
    bg: colors.gray["900"],
    item: colors.green["600"],
    text: colors.gray["400"],
    apply: colors.green["500"],
    cancel: colors.gray["500"],
  },
  canvasPermissionMenu: {
    item: colors.green["600"],
    text: colors.gray["400"],
  },
  selectedUsers: {
    darkText: colors.gray["300"],
    veryDarkText: colors.gray["100"],
    username: colors.gray["300"],
    handle: colors.gray["600"],
    checkIcon: colors.green["500"],
    copyLink: colors.blue["500"],
    permsTab: {
      bg: colors.gray["800"],
      border: colors.gray["700"],
      emailBg: colors.gray["600"],
      addMoreUsers: colors.blue["500"],
      apply: colors.green["500"],
      no: colors.gray["500"],
      inputText: colors.gray["300"],
    },
  },
  modal: {
    bg: colors.modalBg,
    contentBg: colors.black.appBlack,
    border: colors.gray["700"],
    xIcon: colors.gray["300"],
  },
  sidebar: {
    bg: colors.gray["900"],
    arrowIconsHoverBg: colors.white01,
    navItems: {
      default: colors.gray["300"],
      selected: colors.white,
    },
    text: colors.white,
    studionav: {
      bg: colors.black.appBlack,
      text: colors.white,
      textSecondary: colors.gray["500"],
      textSecondaryHover: colors.gray["300"],
      hoverBg: colors.gray["700"],
      focusBg: colors.gray["600"],
      addStudioColor: colors.gray["300"],
      buttonHover: colors.gray["400"],
      buttonHoverBg: colors.white07,
    },
    addStudio: {
      bg: colors.gray["500"],
      hoverText: colors.gray["700"],
      text: colors.gray["100"],
    },
    collectionTree: {
      kebabHoverGray: colors.gray["0"],
      kebabDefaultGray: colors.gray["300"],
      no: colors.gray["500"],
      apply: colors.green["500"],
    },
    draftsTree: {
      bg: colors.white,
      node: colors.gray["700"],
      nodeName: colors.white,
    },
  },
  editModal: {
    avatarBorder: colors.avatarBorder,
    editIconBg: colors.gray["900"],
    heading: colors.gray["300"],
    divider: colors.gray["600"],
  },
  styledTextInput: {
    bg: colors.gray["900"],
    errorColor: colors.pinkRed,
    warningColor: colors.yellow["800"],
    border: colors.gray["700"],
    focusBorder: colors.vividBlue,
  },
  studioSettings: {
    box1: colors.black.appBlack,
    box2: colors.gray["900"],
    box3: colors.gray["800"],
    settingsHeading: colors.white,
    tab: {
      selectedBg: colors.white07,
      name: colors.gray["300"],
      countBg: colors.gray["600"],
    },
    role: {
      selectedBg: colors.white07,
      name: colors.gray["300"],
      indicatorBg: colors.gray["400"],
      syncPermissionColor: colors.vividBlue,
    },
    member: {
      selectedBg: colors.white07,
      name: colors.gray["300"],
    },
    box3Styles: {
      leftArrowIcon: colors.gray["600"],
      systemRole: colors.blue["500"],
      countBg: colors.gray["600"],
      peopleIcon: colors.blue["400"],
      horizontalIcon: colors.gray["300"],
      plusIcon: colors.gray["300"],
      xIcon: colors.gray["300"],
      tokenBorder: colors.gray["700"],
      danger: colors.pinkRed,
    },
  },
  searchUsers: {
    hoverBg: colors.white07,
    peopleIcon: colors.blue["400"],
    emailBg: colors.gray["700"],
    emailText: colors.gray["300"],
  },
  permissionTree: {
    inputBorder: colors.gray["700"],
    divider: colors.gray["700"],
  },
  commandMenu: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    hoverBg: colors.gray["800"],
    optionsText: colors.gray["600"],
    fileIcon: colors.gray["500"],
  },
  mentionDropdown: {
    text: colors.gray["300"],
    hoverBg: colors.gray["800"],
    countBg: colors.countBg,
    countColor: colors.gray["500"],
  },
  mergeRequest: {
    bg: colors.gray["900"],
    border: colors.gray["700"],
    username: colors.gray["300"],
    commitMessage: colors.gray["400"],
    errorMsg: colors.red["500"],
  },
  toggleSwitch: {
    bg: colors.green["300"],
    border: colors.green["500"],
    knobBg: colors.green["500"],
    knobBorder: colors.green["500"],
  },
  diff: {
    messageBg: colors.gray["800"],
    message: colors.gray["300"],
    arrowIcons: colors.gray["600"],
    acceptColor: colors.green["400"],
    rejectColor: colors.red["400"],
    actionIcons: colors.gray["600"],
    actionButtonsHoverBg: colors.gray["800"],
    greenBg: colors.green["900"],
    redBg: colors.red["900"],
  },
  leaf: {
    text: {
      link: colors.vividBlue,
      darkText: colors.gray["200"],
    },
    yellowBorder: colors.yellow["900"],
  },
  text: {
    emphasize: colors.gray["0"],
    // default: colors.gray["300"],
    default: colors.white,
    muted: colors.gray["500"],
    subtle: colors.gray["600"],
  },
  landing: {
    text: colors.black.appBlack,
    textHover: colors.white,
    hero: {
      bg: colors.gray["0"],
      video: {
        videoBg: colors.videoBg,
        text: colors.white,
      },
      btn: {
        text: colors.gray["900"],
        textHover: colors.gray["900"],
      },
    },
    testimonials: {
      bg: colors.white,
      text: colors.gray["800"],
      btn: {
        bg: colors.gray["0"],
        text: colors.gray["900"],
      },
      box: {
        bg: colors.gray["0"],
        subText: colors.gray["700"],
        selectedIndex: colors.gray["200"],
      },
    },
    faq: {
      box1: {
        bg: colors.gray["0"],
        heading: colors.gray["700"],
        text: colors.gray["800"],
        subText: colors.gray["700"],
      },
      box2: {
        bg: colors.gray["0"],
      },
      text: colors.black.appBlack,
      faqItem: {
        question: colors.gray["800"],
        answer: colors.gray["700"],
        icon: {
          bg: colors.gray["0"],
          text: colors.gray["900"],
        },
      },
    },
    communityCard: {
      heading: colors.gray["800"],
      subHeading: colors.gray["700"],
    },
  },
  pricingPage: {
    text: colors.black.appBlack,
    subText: colors.gray["800"],
    hero: {
      bg: colors.white,
    },
    box: {
        bg: colors.gray["0"],
        text: colors.gray["700"],
    },
    noProfitCard: {
      heading: colors.gray["800"],
      subHeading: colors.gray["700"],
      btn: {
        bg: colors.white,
        text: colors.bunker
      }
    },
  },
};
