import colors, { vividBlue } from "./utils/Colors";

export const lightTheme = {
  prevNextButtons: {
    bg: colors.white,
    arrow: colors.gray["500"],
    hoverBg: colors.gray["0"],
    prevText: colors.suvaGray,
    title: colors.gray["700"],
  },
  brands: {
    ...colors.brands,
  },
  auth: {
    bg: colors.gray["0"],
    header: {
      bg: colors.white,
      text: colors.gray["400"],
    },
    home: {
      bg: colors.white,
      box1: {
        heading: colors.gray["900"],
        defiProject: colors.green["600"],
        subHeading: colors.gray["400"],
      },
      box2: {
        bg: colors.darkGrayishBlue,
        heading: colors.white,
        link: colors.gray["500"],
        linkBorder: colors.gray["77"],
        cardBg: colors.white,
        image: colors.gray["700"],
        cardHead: colors.gray["900"],
        cardSubHead: colors.gray["500"],
        divider: colors.veryLightGray,
      },
      box3: {
        bg: colors.white,
        head: colors.shark,
        subHead: colors.suvaGray,
        points: colors.gray["500"],
        iconBg: colors.green["0"],
        buttonBg: colors.gray["0"],
        buttonText: colors.bunker,
      },
      box4: {
        bg: colors.white,
        heading: colors.hexaChromeBlack,
        card1: colors.papayaWhip,
        card2: colors.harmonies,
        card3: colors.hawkiesBlue,
        title: colors.gray["900"],
        description: colors.suvaGray,
      },
      box5: {
        bg: colors.mostlyWhite,
        heading: colors.black["0"],
        cardBg: colors.white,
        name: colors.gray["900"],
        company: colors.gray["500"],
        feedback: colors.gray["900"],
      },
      footer: {
        bg: colors.hexaChromeBlack,
        text: colors.white,
      },
    },
    setup: {
      border: colors.pattensBlue,
      bg: colors.white,
      heading: colors.noColorName,
      text: colors.bunker,
      avatarBorder: colors.avatarBorder,
      icon: colors.gray["500"],
    },
    reset: {
      border: colors.pattensBlue,
      bg: colors.white,
    },
    signin: {
      heading: colors.gray["700"],
      arrowIcon: colors.bunker,
      privacyPolicy: colors.mediumStateBlue,
      discordText: colors.white,
      discordBorder: colors.avatarBorder,
      discordButton: colors.mediumStateBlue,
      slackText: colors.white,
      slackButton: colors.brands.slack,
      slackBorder: colors.brands.slack,
      divider: colors.veryLightGray,
      iconsBg: colors.gray["0"],
      twitter: colors.buttonBlue,
      twitterText: colors.vividBlue,
      mail: colors.darkCyanBlue,
      emailBorder: colors.geyser,
      emailText: colors.bunker,
      forgotMessage: colors.gray["500"],
      otp: colors.vividBlue,
      otpMessage: colors.gray["500"],
      bg: colors.white,
      border: colors.pattensBlue,
      progressBar: colors.green["400"],
    },
    onboarding: {
      bg: colors.gray["100"],
      description: colors.gray["700"],
    },
  },
  discordIntegration: {
    description: colors.gray["500"],
    createCardBorder: colors.green["500"],
  },
  notionImport: {
    checkIcon: colors.green["500"],
    heading: colors.hexaChromeBlack,
    failedMsg: colors.red["600"],
    uploadBoxBg: colors.green["100"],
    uploadDisabled: colors.gray["0"],
    infoIcon: colors.gray["77"],
    importText: colors.gray["500"],
    border: colors.geyser,
    importTypeHover: colors.gray["0"],
  },
  createStudioLoader: {
    bg: colors.white,
  },
  postInFeed: {
    cardBg: colors.white,
    textLight: colors.gray["500"],
    text: colors.gray["700"],
    textSelect: colors.vividBlue,
    textBlack: colors.bunker,
    border: colors.geyser,
    commentsBg: colors.postCommentsBg,
    selCommentBg: colors.gray["300"],
    likeOverlayBg: colors.white,
  },
  notifications: {
    bg: colors.white,
    spinner: colors.green["500"],
    inboxIcon: colors.blue["400"],
    emptyHeading: colors.gray["800"],
    emptyMessage: colors.gray["700"],
    endBorder: colors.gray["200"],
    filters: {
      border: colors.gray["0"],
      selected: {
        text: colors.green["800"],
        bg: colors.green["0"],
      },
      unSelected: {
        text: colors.gray["600"],
        bg: colors.gray["0"],
      },
    },
    messages: {
      hoverBg: colors.gray["100"],
      imageBorder: colors.gray["300"],
      imageText: colors.black["0"],
      message: colors.hexaChromeBlack,
      repliesText: colors.suvaGray,
      time: colors.gray["500"],
    },
    primaryButton: {
      color: colors.white,
      border: colors.avatarBorder,
    },
    tabNav: {
      bg: colors.gray["0"],
      selected: {
        bg: colors.white,
        text: colors.black["0"],
      },
      unSelected: {
        text: colors.gray["500"],
      },
    },
    users: {
      black: colors.black["0"],
      selectedBorder: colors.blue["500"],
      border: colors.gray["300"],
      counterBg: colors.green["600"],
      counter: colors.white,
    },
    settings: {
      box1: {
        bg: colors.gray["100"],
        border: colors.gray["200"],
        heading: colors.gray["500"],
        text: colors.darkCyanBlue,
        xIcon: colors.gray["900"],
      },
      box2: {
        platform: colors.black["0"],
        border: colors.geyser,
      },
    },
  },
  bipMarks: {
    border: colors.gray["200"],
    scrollBg: colors.gray["100"],
    icon: colors.blue["400"],
    endMessage: colors.gray["700"],
    bipMessage: colors.gray["600"],
    trashIcon: colors.gray["300"],
  },
  contributorsList: {
    stack: {
      bg: colors.veryLightGray,
    },
    list: {
      text: colors.gray["500"],
      cardHoverBg: colors.gray["0"],
      name: colors.gray["800"],
    },
  },
  canvasItem: {
    text: colors.gray["600"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    nodeName: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  fakeSelection: {
    text: colors.white,
    bg: colors.selectBlue,
  },
  languageItem: {
    text: colors.gray["600"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    nodeName: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  brachItem: {
    text: colors.gray["500"],
    hoverBg: colors.white07,
    border: colors.gray["500"],
    selectedNodeName: colors.gray["300"],
  },
  collectionItem: {
    item: colors.gray["600"],
    itemHoverBg: colors.gray["800"],
    nodeName: colors.gray["500"],
    hoverBg: colors.white07,
    selectedNodeName: colors.gray["300"],
  },
  toolbar: {
    bg: colors.white,
    activeIcon: colors.blue["500"],
    normalIcon: colors.gray["800"],
  },
  blockWrapper: {
    border: colors.white00,
    hoverBg: colors.gray["0"],
    username: colors.gray["800"],
    time: colors.gray["500"],
    icon: colors.gray["400"],
    highlight: colors.gray["200"],
  },
  callout: {
    info: colors.gray["100"],
    tip: colors.blue["100"],
    success: colors.green["100"],
    alert: colors.yellow["100"],
    danger: colors.red["100"],
    hintText: colors.gray["500"],
  },
  image: {
    caption: colors.gray["500"],
  },
  table: {
    border: colors.blue["300"],
  },
  drawio: {
    hintText: colors.gray["700"],
    emptyHintText: colors.gray["700"],
    imageBg: colors.white,
  },
  headings: {
    text: colors.gray["800"],
  },
  chip: {
    bg: colors.gray["100"],
    icon: colors.gray["500"],
  },
  toast: {
    success: colors.green["500"],
    error: colors.red["600"],
    warning: colors.yellow["800"],
    info: colors.blue["500"],
    text: colors.gray["800"],
    closeIcon: colors.gray["500"],
    bg: colors.white,
    icon: colors.white,
  },
  verticalDivider: {
    border: colors.gray["400"],
  },
  imageWithName: {
    color: colors.white,
    border: colors.white,
  },
  element: {
    bg: colors.yellow["200"],
  },
  checklistBlock: {
    text: colors.gray["700"],
  },
  orderedListBlock: {
    text: colors.gray["700"],
  },
  unOrderedListBlock: {
    text: colors.gray["700"],
  },
  attachmentBlock: {
    bg: colors.gray["100"],
    acceptBg: colors.green["100"],
    rejectBg: colors.red["100"],
    selectedBorder: colors.blue["700"],
    border: colors.gray["700"],
  },
  codeBlock: {
    text: colors.gray["83"],
    bg: colors.lightHexaChromeBlack,
    hintText: colors.gray["500"],
  },
  quoteBlock: {
    text: colors.gray["700"],
    borderColor: colors.gray["300"],
  },
  inlineCode: {
    text: colors.gray["800"],
  },
  defaultBlock: {
    text: colors.gray["700"],
  },
  subTextBlock: {
    text: colors.gray["500"],
  },
  dividerBlock: {
    default: colors.gray["500"],
    selected: colors.gray["700"],
  },
  excalidraw: {
    hintText: colors.suvaGray,
  },
  imageBlock: {
    bg: colors.gray["100"],
    acceptBg: colors.green["100"],
    rejectBg: colors.red["100"],
    selectedBorder: colors.blue["700"],
    border: colors.gray["700"],
    resize: colors.white,
    resizeBg: colors.black["0"],
  },
  TOCBlock: {
    bg: colors.gray["100"],
    textColor: colors.gray["700"],
  },
  canvasHeaderActions: {
    buttonGroups: {
      border: colors.white,
    },
    cancel: colors.red["600"],
    lightText: colors.gray["500"],
    overlayBg: colors.white,
    inputBorder: colors.geyser,
    message: colors.gray["700"],
  },
  canvasUserPermissions: {
    bg: colors.gray["0"],
    avatarText: colors.gray["700"],
    anchorBg: colors.gray["100"],
  },
  layout: {
    sidebar: {
      bg: colors.gray["900"],
      text: colors.gray["300"],
    },
    user: {
      text: colors.white,
      bg: colors.white05,
      hoverBg: colors.white01,
      notificationCountBg: colors.green["600"],
    },
    bg: colors.gray["0"],
  },
  studioLayout: {
    bg: colors.gray["0"],
    white: colors.white,
    headerBg: colors.gray["0"],
  },
  previewEditor: {
    bg: colors.white,
    headerBg: colors.gray["0"],
    headerBorder: colors.gray["300"],
    canvasTitle: colors.gray["700"],
  },
  layoutFAB: {
    bg: colors.gray["100"],
    color: colors.gray["800"],
  },
  reelCard: {
    bg: colors.white,
    border: colors.geyser,
    avatarBorder: colors.gray["300"],
    followButton: colors.green["600"],
    text: {
      username: colors.black["0"],
      studioname: colors.gray["700"],
      grayLight: colors.gray["500"],
      time: colors.gray["700"],
      reelMessage: colors.gray["700"],
      repliesText: colors.gray["500"],
      hintText: colors.suvaGray,
    },
    editor: {
      bg: colors.gray["0"],
      border: "transparent",
      text: colors.gray["600"],
      button: {
        text: colors.gray["500"],
        hoverBg: colors.gray["10"],
        hoverText: colors.gray["700"],
      },
      link: {
        hoverBorder: colors.gray["700"],
        text: colors.gray["500"],
        hoverText: colors.gray["600"],
      },
    },
    comment: {
      bg: colors.harmonies,
      text: colors.hexaChromeBlack,
      time: colors.suvaGray,
      downIcon: colors.gray["400"],
      repliesText: colors.gray["500"],
    },
  },
  about: {
    bg: colors.white,
    border: colors.geyser,
    avatarBorder: colors.avatarBorder,
    editButtonHoverBg: colors.gray["0"],
    tokenBorder: colors.gray["200"],
    text: {
      avatarText: colors.gray["700"],
      displayName: colors.gray["700"],
      handle: colors.gray["500"],
      description: colors.gray["700"],
      joinButton: colors.green["600"],
      joinedButton: colors.gray["600"],
      token: colors.gray["400"],
      editIconColor: colors.gray["700"],
      calendarIcon: colors.gray["400"],
      date: colors.gray["400"],
      twitterIcon: colors.gray["0"],
      globeIcon: colors.gray["400"],
      linkColor: colors.blue["400"],
      linkHoverColor: colors.blue["300"],
      location: colors.gray["400"],
      followCount: colors.gray["400"],
      pencilIcon: colors.gray["700"],
    },
  },
  newRightRail: {
    bg: colors.white,
    border: colors.geyser,
  },
  profile: {
    bg: colors.white,
    border: colors.geyser,
    avatarBorder: colors.avatarBorder,
    studioBorder: colors.gray["300"],
    editButtonHoverBg: colors.gray["0"],
    text: {
      username: colors.gray["700"],
      handle: colors.gray["500"],
      bio: colors.gray["700"],
      followButton: colors.green["600"],
      followingButton: colors.gray["600"],
      calendarIcon: colors.gray["400"],
      date: colors.gray["400"],
      twitterIcon: colors.gray["0"],
      globeIcon: colors.gray["400"],
      linkColor: colors.blue["400"],
      linkHoverColor: colors.blue["300"],
      location: colors.gray["400"],
      followCount: colors.gray["400"],
      pencilIcon: colors.gray["700"],
    },
  },
  studioCard: {
    bg: colors.white,
    border: colors.gray["200"],
    text: {
      displayname: colors.gray["700"],
      handle: colors.gray["400"],
      joinButton: colors.green["600"],
      joinedButton: colors.gray["600"],
      description: colors.gray["700"],
      members: colors.gray["400"],
    },
  },
  userCard: {
    bg: colors.white,
    border: colors.gray["200"],
    text: {
      username: colors.gray["700"],
      handle: colors.gray["400"],
      followButton: colors.green["600"],
      followingButton: colors.gray["600"],
      followers: colors.gray["400"],
    },
  },
  addComment: {
    bg: colors.white,
    border: colors.geyser,
    cancel: colors.gray["500"],
    postBg: colors.green["500"],
    postBorder: colors.green["500"],
    postText: colors.white,
    errorColor: colors.pinkRed,
  },
  addReel: {
    bg: colors.white,
    border: colors.geyser,
    heading: colors.hexaChromeBlack,
    closeIcon: colors.suvaGray,
    hintText: colors.suvaGray,
  },
  thread: {
    bg: colors.white,
    border: colors.geyser,
    menuBg: colors.white,
    highlightedTextBorder: colors.yellow["600"],
    text: {
      highlightedText: colors.gray["500"],
      date: colors.gray["500"],
      message: colors.gray["700"],
      username: colors.gray["700"],
      repliesText: colors.gray["700"],
      resolve: colors.gray["500"],
    },
  },
  reel: {
    bg: colors.white,
    border: colors.geyser,
    comment: {
      bg: colors.harmonies,
      text: colors.hexaChromeBlack,
      time: colors.suvaGray,
      downIcon: colors.gray["400"],
      repliesText: colors.gray["500"],
      highlightTextBorder: colors.yellow["600"],
      highlightText: colors.gray["500"],
      message: colors.gray["700"],
    },
  },
  canvasHeader: {
    bg: colors.gray["0"],
  },
  canvasTitle: {
    title: colors.gray["800"],
    border: colors.geyser,
    hintMessage: colors.gray["500"],
    loginMessage: colors.suvaGray,
    loginButton: colors.green["500"],
  },
  rightRailContainer: {
    bg: colors.gray["0"],
  },
  canvasTimeline: {
    itemBg: colors.gray["300"],
    commit: {
      hoverBg: colors.veryLightGray,
      date: colors.gray["500"],
      message: colors.hexaChromeBlack,
    },
  },
  mentionsInput: {
    users: {
      bg: colors.white,
      selectedBg: colors.veryLightShadeOfGray,
    },
    mentionedText: colors.green["500"],
  },
  blockReactions: {
    bg: colors.white,
    border: colors.geyser,
  },
  toc: {
    bg: colors.gray["0"],
    text: colors.gray["700"],
    activeText: colors.gray["800"],
    border: colors.white,
  },
  rightRailPermissions: {
    lightText: colors.gray["500"],
    darkText: colors.gray["700"],
    veryDarkText: colors.gray["800"],
    copyLink: colors.gray["500"],
    inviteUsers: colors.green["500"],
  },
  canvasPublicAccessOverlay: {
    bg: colors.white,
    item: colors.green["600"],
    text: colors.bunker,
    apply: colors.green["500"],
    cancel: colors.gray["500"],
  },
  collectionPublicAccessOverlay: {
    bg: colors.white,
    item: colors.green["600"],
    text: colors.bunker,
    apply: colors.green["500"],
    cancel: colors.gray["500"],
  },
  canvasPermissionMenu: {
    item: colors.green["600"],
    text: colors.bunker,
  },
  selectedUsers: {
    darkText: colors.gray["700"],
    veryDarkText: colors.gray["800"],
    username: colors.gray["700"],
    handle: colors.gray["400"],
    checkIcon: colors.green["500"],
    copyLink: colors.green["500"],
    permsTab: {
      bg: colors.white,
      border: colors.geyser,
      emailBg: colors.gray["0"],
      addMoreUsers: colors.green["500"],
      apply: colors.green["500"],
      no: colors.gray["500"],
      inputText: colors.gray["700"],
    },
  },
  commandMenu: {
    bg: colors.white,
    border: colors.white,
    hoverBg: colors.gray["100"],
    optionsText: colors.gray["400"],
    fileIcon: colors.gray["500"],
  },
  mentionDropdown: {
    text: colors.noColorName,
    hoverBg: colors.gray["100"],
    countBg: colors.countBg,
    countColor: colors.bunker,
  },
  editModal: {
    avatarBorder: colors.avatarBorder,
    editIconBg: colors.white,
    heading: colors.bunker,
    divider: colors.veryLightGray,
  },
  styledTextInput: {
    bg: colors.white,
    errorColor: colors.pinkRed,
    warningColor: colors.yellow["800"],
    border: colors.geyser,
    focusBorder: colors.vividBlue,
  },
  studioSettings: {
    box1: colors.aliceBlue,
    box2: colors.gray["0"],
    box3: colors.white,
    settingsHeading: colors.gray["500"],
    tab: {
      selectedBg: colors.gray["200"],
      name: colors.bunker,
      countBg: colors.countBg,
    },
    role: {
      selectedBg: colors.gray["200"],
      name: colors.bunker,
      indicatorBg: colors.gray["400"],
      syncPermissionColor: colors.vividBlue,
    },
    member: {
      selectedBg: colors.gray["200"],
      name: colors.bunker,
    },
    box3Styles: {
      leftArrowIcon: colors.gray["200"],
      systemRole: colors.blue["500"],
      countBg: colors.countBg,
      peopleIcon: colors.blue["400"],
      horizontalIcon: colors.bunker,
      plusIcon: colors.bunker,
      xIcon: colors.bunker,
      tokenBorder: colors.geyser,
      danger: colors.pinkRed,
    },
  },
  searchUsers: {
    hoverBg: colors.hawkesBlue,
    peopleIcon: colors.blue["400"],
    emailBg: colors.gray["200"],
    emailText: colors.hexaChromeBlack,
  },
  permissionTree: {
    inputBorder: colors.geyser,
    divider: colors.geyser,
    rolePermOverridden: colors.gray["400"],
  },
  toggleSwitch: {
    bg: colors.gray["300"],
    border: colors.geyser,
    toggleKnobBg: colors.gray["0"],
    knobBorder: colors.gray["0"],
  },
  modal: {
    bg: colors.modalBg,
    contentBg: colors.white,
    border: colors.white,
    xIcon: colors.gray["900"],
  },
  mergeRequest: {
    bg: colors.white,
    border: colors.gray["77"],
    username: colors.bunker,
    commitMessage: colors.gray["600"],
    errorMsg: colors.red["600"],
  },
  diff: {
    messageBg: colors.gray["0"],
    message: colors.gray["700"],
    arrowIcons: colors.gray["400"],
    acceptColor: colors.green["600"],
    rejectColor: colors.red["600"],
    actionIcons: colors.gray["400"],
    actionButtonsHoverBg: colors.gray["10"],
    greenBg: colors.green["0"],
    redBg: colors.red["0"],
  },
  leaf: {
    text: {
      link: colors.vividBlue,
      darkText: colors.gray["800"],
    },
    yellowBorder: colors.yellow["300"],
  },
  handle: {
    text: colors.gray["500"],
  },
  sidebar: {
    arrowIconsHoverBg: colors.white01,
    bg: colors.gray["900"],
    navItems: {
      default: colors.gray["300"],
      selected: colors.white,
    },
    text: colors.white,
    studionav: {
      bg: colors.gray["800"],
      text: colors.white,
      textSecondary: colors.gray["500"],
      textSecondaryHover: colors.gray["300"],
      hoverBg: colors.gray["700"],
      focusBg: colors.gray["600"],
      addStudioColor: colors.gray["300"],
      buttonHover: colors.gray["400"],
      buttonHoverBg: colors.white07,
    },
    addStudio: {
      bg: colors.gray["500"],
      hoverText: colors.gray["700"],
      text: colors.gray["100"],
    },
    collectionTree: {
      kebabHoverGray: colors.gray["0"],
      kebabDefaultGray: colors.gray["300"],
      no: colors.gray["500"],
      apply: colors.green["500"],
    },
    draftsTree: {
      bg: colors.white,
      node: colors.gray["700"],
      nodeName: colors.white,
    },
  },
  btn: {
    primary: {
      text: colors.white,
      bg: colors.green["500"],
      hoverBg: colors.green["700"],
      disabledBg: colors.green["200"],
      focusBg: colors.green["900"],
    },
    danger: {
      text: colors.red["500"],
      hoverText: colors.white,
      hoverBg: colors.red["700"],
      selectedText: colors.white,
      icon: colors.red["500"],
      hoverIcon: colors.white,
    },
  },
  border: {
    default: colors.gray["200"],
    muted: colors.gray["300"],
    subtle: colors.gray["700"],
    ultraSubtle: colors.gray["400"],
  },
  bg: {
    subtle: colors.gray["100"],
    lightgray: colors.gray["200"],
    ultraSubtle: colors.gray["10"],
    superUltraSubtle: colors.gray["0"],
  },
  text: {
    emphasize: colors.gray["800"],
    default: colors.gray["700"],
    muted: colors.gray["500"],
    subtle: colors.gray["400"],
    green: colors.green["600"],
  },
  success: {
    fg: colors.green["500"],
    emphasis: colors.green["300"],
    muted: colors.green["900"],
    subtle: colors.green["100"],
  },
  attention: {
    fg: colors.yellow["500"],
    emphasis: colors.yellow["300"],
    muted: colors.yellow["900"],
    subtle: colors.yellow["100"],
  },
  severe: {
    fg: colors.orange["500"],
    emphasis: colors.orange["300"],
    muted: colors.orange["900"],
    subtle: colors.orange["100"],
  },
  danger: {
    fg: colors.red["500"],
    emphasis: colors.red["300"],
    muted: colors.red["900"],
    subtle: colors.red["100"],
  },
  open: {
    fg: colors.green["500"],
    emphasis: colors.green["300"],
    muted: colors.green["900"],
    subtle: colors.green["100"],
  },
  closed: {
    fg: colors.red["500"],
    emphasis: colors.red["300"],
    muted: colors.red["900"],
    subtle: colors.red["100"],
  },
  done: {
    fg: colors.purple["500"],
    emphasis: colors.purple["300"],
    muted: colors.purple["900"],
    subtle: colors.purple["100"],
  },
  sponsors: {
    fg: colors.pink["500"],
    emphasis: colors.purple["300"],
    muted: colors.purple["900"],
    subtle: colors.purple["100"],
  },
  primer: {
    border: {
      active: colors.gray["700"],
    },
  },
  landing: {
    text: colors.black.appBlack,
    textHover: colors.gray["900"],
    hero: {
      bg: colors.gray["0"],
      video: {
        videoBg: colors.videoBg,
        text: colors.white,
      },
      btn: {
        text: colors.gray["900"],
        textHover: colors.gray["900"],
      },
    },
    testimonials: {
      bg: colors.white,
      text: colors.gray["800"],
      btn: {
        bg: colors.gray["0"],
        text: colors.gray["900"],
      },
      box: {
        bg: colors.gray["0"],
        subText: colors.gray["700"],
        selectedIndex: colors.gray["200"],
      },
    },
    faq: {
      box1: {
        bg: colors.gray["0"],
        heading: colors.gray["700"],
        text: colors.gray["800"],
        subText: colors.gray["700"],
      },
      box2: {
        bg: colors.gray["0"],
      },
      text: colors.black.appBlack,
      faqItem: {
        question: colors.gray["800"],
        answer: colors.gray["700"],
        icon: {
          bg: colors.gray["0"],
          text: colors.gray["900"],
        },
      },
    },
    communityCard: {
      heading: colors.gray["800"],
      subHeading: colors.gray["700"],
    },
  },
  pricingPage: {
    text: colors.black.appBlack,
    subText: colors.gray["800"],
    hero: {
      bg: colors.white,
    },
    box: {
      bg: colors.gray["0"],
      text: colors.gray["700"],
    },
    noProfitCard: {
      heading: colors.gray["800"],
      subHeading: colors.gray["700"],
      btn: {
        bg: colors.white,
        text: colors.bunker,
      },
    },
  },
};
